# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dex_api_python
from dex_api_python.models.inline_response20064 import InlineResponse20064  # noqa: E501
from dex_api_python.rest import ApiException


class TestInlineResponse20064(unittest.TestCase):
    """InlineResponse20064 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20064(self):
        """Test InlineResponse20064"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dex_api_python.models.inline_response20064.InlineResponse20064()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
