# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dex_api_python
from dex_api_python.models.tickers import Tickers  # noqa: E501
from dex_api_python.rest import ApiException


class TestTickers(unittest.TestCase):
    """Tickers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTickers(self):
        """Test Tickers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dex_api_python.models.tickers.Tickers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
