# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dex_api_python
from dex_api_python.api.slash_api import SlashApi  # noqa: E501
from dex_api_python.rest import ApiException


class TestSlashApi(unittest.TestCase):
    """SlashApi unit test stubs"""

    def setUp(self):
        self.api = dex_api_python.api.slash_api.SlashApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_query_slash(self):
        """Test case for query_slash

        Query validator slash info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
