# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20038 import InlineResponse20038  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20038(unittest.TestCase):
    """InlineResponse20038 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20038(self):
        """Test InlineResponse20038"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20038.InlineResponse20038()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
