# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.comment_ref import CommentRef  # noqa: E501
from swagger_client.rest import ApiException


class TestCommentRef(unittest.TestCase):
    """CommentRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommentRef(self):
        """Test CommentRef"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.comment_ref.CommentRef()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
