# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.amount2 import Amount2  # noqa: E501
from swagger_client.rest import ApiException


class TestAmount2(unittest.TestCase):
    """Amount2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAmount2(self):
        """Test Amount2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.amount2.Amount2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
