# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.distribution_api import DistributionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDistributionApi(unittest.TestCase):
    """DistributionApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.distribution_api.DistributionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_donate_to_community_pool(self):
        """Test case for donate_to_community_pool

        Donate to the community pool  # noqa: E501
        """
        pass

    def test_get_all_rewards(self):
        """Test case for get_all_rewards

        Get the total rewards balance from all delegations  # noqa: E501
        """
        pass

    def test_get_community_pool(self):
        """Test case for get_community_pool

        Community pool parameters  # noqa: E501
        """
        pass

    def test_get_distribution_info(self):
        """Test case for get_distribution_info

        Validator distribution information  # noqa: E501
        """
        pass

    def test_get_distribution_params(self):
        """Test case for get_distribution_params

        Fee distribution parameters  # noqa: E501
        """
        pass

    def test_get_outstanding_rewards(self):
        """Test case for get_outstanding_rewards

        Fee distribution outstanding rewards of a single validator  # noqa: E501
        """
        pass

    def test_get_reward_by_validator(self):
        """Test case for get_reward_by_validator

        Query a delegation reward  # noqa: E501
        """
        pass

    def test_get_validator_rewards(self):
        """Test case for get_validator_rewards

        Commission and self-delegation rewards of a single validator  # noqa: E501
        """
        pass

    def test_get_withdraw_address(self):
        """Test case for get_withdraw_address

        Get the rewards withdrawal address  # noqa: E501
        """
        pass

    def test_set_withdraw_address(self):
        """Test case for set_withdraw_address

        Replace the rewards withdrawal address  # noqa: E501
        """
        pass

    def test_withdraw_all_rewards(self):
        """Test case for withdraw_all_rewards

        Withdraw all the delegator's delegation rewards  # noqa: E501
        """
        pass

    def test_withdraw_all_validator_rewards(self):
        """Test case for withdraw_all_validator_rewards

        Withdraw the validator's rewards  # noqa: E501
        """
        pass

    def test_withdraw_rewards_by_validator(self):
        """Test case for withdraw_rewards_by_validator

        Withdraw a delegation reward  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
