# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.asset_api import AssetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAssetApi(unittest.TestCase):
    """AssetApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.asset_api.AssetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_whitelist(self):
        """Test case for add_whitelist

        Add forbid whitelist  # noqa: E501
        """
        pass

    def test_burn_token(self):
        """Test case for burn_token

        Burn token  # noqa: E501
        """
        pass

    def test_forbid_addr(self):
        """Test case for forbid_addr

        Forbid address  # noqa: E501
        """
        pass

    def test_forbid_token(self):
        """Test case for forbid_token

        Forbid token  # noqa: E501
        """
        pass

    def test_get_asset_params(self):
        """Test case for get_asset_params

        Get the current asset parameters  # noqa: E501
        """
        pass

    def test_get_forbidden_addresses(self):
        """Test case for get_forbidden_addresses

        query forbidden addresses  # noqa: E501
        """
        pass

    def test_get_reserved_symbols(self):
        """Test case for get_reserved_symbols

        List reserved symbols  # noqa: E501
        """
        pass

    def test_get_token(self):
        """Test case for get_token

        queryToken  # noqa: E501
        """
        pass

    def test_get_token_list(self):
        """Test case for get_token_list

        List tokens  # noqa: E501
        """
        pass

    def test_get_whitelist(self):
        """Test case for get_whitelist

        queryWhitelist  # noqa: E501
        """
        pass

    def test_issue_token(self):
        """Test case for issue_token

        Issue token  # noqa: E501
        """
        pass

    def test_mint_token(self):
        """Test case for mint_token

        Mint token  # noqa: E501
        """
        pass

    def test_modify_token_info(self):
        """Test case for modify_token_info

        Modify token info  # noqa: E501
        """
        pass

    def test_remove_whitelist(self):
        """Test case for remove_whitelist

        Remove forbid whitelist  # noqa: E501
        """
        pass

    def test_transfer_ownership(self):
        """Test case for transfer_ownership

        Transfer ownership  # noqa: E501
        """
        pass

    def test_un_forbid_addr(self):
        """Test case for un_forbid_addr

        UnForbid address  # noqa: E501
        """
        pass

    def test_un_frobid_token(self):
        """Test case for un_frobid_token

        UnForbid token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
