# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.staking_api import StakingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStakingApi(unittest.TestCase):
    """StakingApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.staking_api.StakingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_delegations(self):
        """Test case for get_delegations

        Get all delegations from a delegator  # noqa: E501
        """
        pass

    def test_get_delegations_of_validator(self):
        """Test case for get_delegations_of_validator

        Get all delegations from a validator  # noqa: E501
        """
        pass

    def test_get_delegations_to_validator(self):
        """Test case for get_delegations_to_validator

        Query the current delegation between a delegator and a validator  # noqa: E501
        """
        pass

    def test_get_delegator_txs(self):
        """Test case for get_delegator_txs

        Get all staking txs (i.e msgs) from a delegator  # noqa: E501
        """
        pass

    def test_get_redelegations(self):
        """Test case for get_redelegations

        Get all redelegations (filter by query params)  # noqa: E501
        """
        pass

    def test_get_staking_parameters(self):
        """Test case for get_staking_parameters

        Get the current staking parameter values  # noqa: E501
        """
        pass

    def test_get_staking_pool(self):
        """Test case for get_staking_pool

        Get the current state of the staking pool  # noqa: E501
        """
        pass

    def test_get_undelegations_between(self):
        """Test case for get_undelegations_between

        Query all unbonding delegations between a delegator and a validator  # noqa: E501
        """
        pass

    def test_get_undelegations_of_delegator(self):
        """Test case for get_undelegations_of_delegator

        Get all unbonding delegations from a delegator  # noqa: E501
        """
        pass

    def test_get_undelegations_of_validator(self):
        """Test case for get_undelegations_of_validator

        Get all unbonding delegations from a validator  # noqa: E501
        """
        pass

    def test_get_validator(self):
        """Test case for get_validator

        Query the information from a single validator  # noqa: E501
        """
        pass

    def test_get_validator_of_delegator(self):
        """Test case for get_validator_of_delegator

        Query a validator that a delegator is bonded to  # noqa: E501
        """
        pass

    def test_get_validators(self):
        """Test case for get_validators

        Get all validator candidates. By default it returns only the bonded validators.  # noqa: E501
        """
        pass

    def test_get_validators_of_delegator(self):
        """Test case for get_validators_of_delegator

        Query all validators that a delegator is bonded to  # noqa: E501
        """
        pass

    def test_submit_delegation(self):
        """Test case for submit_delegation

        Submit delegation  # noqa: E501
        """
        pass

    def test_submit_redelegation(self):
        """Test case for submit_redelegation

        Submit a redelegation  # noqa: E501
        """
        pass

    def test_undelegate(self):
        """Test case for undelegate

        Submit an unbonding delegation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
