# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20048 import InlineResponse20048  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20048(unittest.TestCase):
    """InlineResponse20048 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20048(self):
        """Test InlineResponse20048"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20048.InlineResponse20048()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
