# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.market_api import MarketApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMarketApi(unittest.TestCase):
    """MarketApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.market_api.MarketApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_order(self):
        """Test case for cancel_order

        Cancel the order  # noqa: E501
        """
        pass

    def test_cancel_trading_pair(self):
        """Test case for cancel_trading_pair

        Cancel the trading-pair  # noqa: E501
        """
        pass

    def test_create_gte_order(self):
        """Test case for create_gte_order

        Create GTE order in blockchain  # noqa: E501
        """
        pass

    def test_create_ioc_order(self):
        """Test case for create_ioc_order

        Create IOC order in blockchain  # noqa: E501
        """
        pass

    def test_create_trading_pair(self):
        """Test case for create_trading_pair

        Create trading-pair in blockchain  # noqa: E501
        """
        pass

    def test_get_market_params(self):
        """Test case for get_market_params

        Get the current market parameters  # noqa: E501
        """
        pass

    def test_get_order(self):
        """Test case for get_order

        Query order info  # noqa: E501
        """
        pass

    def test_get_orders(self):
        """Test case for get_orders

        Query user order-id list  # noqa: E501
        """
        pass

    def test_get_orders_in_market(self):
        """Test case for get_orders_in_market

        Query trading-pair's orderbook  # noqa: E501
        """
        pass

    def test_get_trading_pair(self):
        """Test case for get_trading_pair

        Query trading-pair info  # noqa: E501
        """
        pass

    def test_modify_price_precision(self):
        """Test case for modify_price_precision

        Modify the price precision of the trading pair in the dex  # noqa: E501
        """
        pass

    def test_query_trading_pairs(self):
        """Test case for query_trading_pairs

        Query all trading-pair infos in blockchain  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
