# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dex_api_python
from dex_api_python.api.expiry_api import ExpiryApi  # noqa: E501
from dex_api_python.rest import ApiException


class TestExpiryApi(unittest.TestCase):
    """ExpiryApi unit test stubs"""

    def setUp(self):
        self.api = dex_api_python.api.expiry_api.ExpiryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_query_redelegation(self):
        """Test case for query_redelegation

        Query redelegation  # noqa: E501
        """
        pass

    def test_query_unbonding(self):
        """Test case for query_unbonding

        Query Unbonding  # noqa: E501
        """
        pass

    def test_query_unlock(self):
        """Test case for query_unlock

        Query Unlock  # noqa: E501
        """
        pass

    def test_querylocked(self):
        """Test case for querylocked

        Query lock tx  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
