# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.auth_api import AuthApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.auth_api.AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_account(self):
        """Test case for get_account

        Get the account information on blockchain  # noqa: E501
        """
        pass

    def test_get_auth_params(self):
        """Test case for get_auth_params

        Get the current auth parameters  # noqa: E501
        """
        pass

    def test_set_referee(self):
        """Test case for set_referee

        Set referee for account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
