# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Account1(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'base_req': 'BaseReq',
        'memo_required': 'bool'
    }

    attribute_map = {
        'base_req': 'base_req',
        'memo_required': 'memo_required'
    }

    def __init__(self, base_req=None, memo_required=None):  # noqa: E501
        """Account1 - a model defined in Swagger"""  # noqa: E501

        self._base_req = None
        self._memo_required = None
        self.discriminator = None

        self.base_req = base_req
        self.memo_required = memo_required

    @property
    def base_req(self):
        """Gets the base_req of this Account1.  # noqa: E501


        :return: The base_req of this Account1.  # noqa: E501
        :rtype: BaseReq
        """
        return self._base_req

    @base_req.setter
    def base_req(self, base_req):
        """Sets the base_req of this Account1.


        :param base_req: The base_req of this Account1.  # noqa: E501
        :type: BaseReq
        """
        if base_req is None:
            raise ValueError("Invalid value for `base_req`, must not be `None`")  # noqa: E501

        self._base_req = base_req

    @property
    def memo_required(self):
        """Gets the memo_required of this Account1.  # noqa: E501


        :return: The memo_required of this Account1.  # noqa: E501
        :rtype: bool
        """
        return self._memo_required

    @memo_required.setter
    def memo_required(self, memo_required):
        """Sets the memo_required of this Account1.


        :param memo_required: The memo_required of this Account1.  # noqa: E501
        :type: bool
        """
        if memo_required is None:
            raise ValueError("Invalid value for `memo_required`, must not be `None`")  # noqa: E501

        self._memo_required = memo_required

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Account1, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Account1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
