# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Proposer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'proposal_id': 'str',
        'proposer': 'str'
    }

    attribute_map = {
        'proposal_id': 'proposal_id',
        'proposer': 'proposer'
    }

    def __init__(self, proposal_id=None, proposer=None):  # noqa: E501
        """Proposer - a model defined in Swagger"""  # noqa: E501

        self._proposal_id = None
        self._proposer = None
        self.discriminator = None

        self.proposal_id = proposal_id
        self.proposer = proposer

    @property
    def proposal_id(self):
        """Gets the proposal_id of this Proposer.  # noqa: E501


        :return: The proposal_id of this Proposer.  # noqa: E501
        :rtype: str
        """
        return self._proposal_id

    @proposal_id.setter
    def proposal_id(self, proposal_id):
        """Sets the proposal_id of this Proposer.


        :param proposal_id: The proposal_id of this Proposer.  # noqa: E501
        :type: str
        """
        if proposal_id is None:
            raise ValueError("Invalid value for `proposal_id`, must not be `None`")  # noqa: E501

        self._proposal_id = proposal_id

    @property
    def proposer(self):
        """Gets the proposer of this Proposer.  # noqa: E501


        :return: The proposer of this Proposer.  # noqa: E501
        :rtype: str
        """
        return self._proposer

    @proposer.setter
    def proposer(self, proposer):
        """Sets the proposer of this Proposer.


        :param proposer: The proposer of this Proposer.  # noqa: E501
        :type: str
        """
        if proposer is None:
            raise ValueError("Invalid value for `proposer`, must not be `None`")  # noqa: E501

        self._proposer = proposer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Proposer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Proposer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
