# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Comment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'height': 'int',
        'sender': 'Address',
        'token': 'str',
        'donation': 'int',
        'title': 'str',
        'content': 'str',
        'content_type': 'int',
        'references': 'list[CommentRef]',
        'tx_hash': 'str'
    }

    attribute_map = {
        'id': 'id',
        'height': 'height',
        'sender': 'sender',
        'token': 'token',
        'donation': 'donation',
        'title': 'title',
        'content': 'content',
        'content_type': 'content_type',
        'references': 'references',
        'tx_hash': 'tx_hash'
    }

    def __init__(self, id=None, height=None, sender=None, token=None, donation=None, title=None, content=None, content_type=None, references=None, tx_hash=None):  # noqa: E501
        """Comment - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._height = None
        self._sender = None
        self._token = None
        self._donation = None
        self._title = None
        self._content = None
        self._content_type = None
        self._references = None
        self._tx_hash = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if height is not None:
            self.height = height
        if sender is not None:
            self.sender = sender
        if token is not None:
            self.token = token
        if donation is not None:
            self.donation = donation
        if title is not None:
            self.title = title
        if content is not None:
            self.content = content
        if content_type is not None:
            self.content_type = content_type
        if references is not None:
            self.references = references
        if tx_hash is not None:
            self.tx_hash = tx_hash

    @property
    def id(self):
        """Gets the id of this Comment.  # noqa: E501


        :return: The id of this Comment.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Comment.


        :param id: The id of this Comment.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def height(self):
        """Gets the height of this Comment.  # noqa: E501


        :return: The height of this Comment.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this Comment.


        :param height: The height of this Comment.  # noqa: E501
        :type: int
        """

        self._height = height

    @property
    def sender(self):
        """Gets the sender of this Comment.  # noqa: E501


        :return: The sender of this Comment.  # noqa: E501
        :rtype: Address
        """
        return self._sender

    @sender.setter
    def sender(self, sender):
        """Sets the sender of this Comment.


        :param sender: The sender of this Comment.  # noqa: E501
        :type: Address
        """

        self._sender = sender

    @property
    def token(self):
        """Gets the token of this Comment.  # noqa: E501


        :return: The token of this Comment.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this Comment.


        :param token: The token of this Comment.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def donation(self):
        """Gets the donation of this Comment.  # noqa: E501


        :return: The donation of this Comment.  # noqa: E501
        :rtype: int
        """
        return self._donation

    @donation.setter
    def donation(self, donation):
        """Sets the donation of this Comment.


        :param donation: The donation of this Comment.  # noqa: E501
        :type: int
        """

        self._donation = donation

    @property
    def title(self):
        """Gets the title of this Comment.  # noqa: E501


        :return: The title of this Comment.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Comment.


        :param title: The title of this Comment.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def content(self):
        """Gets the content of this Comment.  # noqa: E501


        :return: The content of this Comment.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this Comment.


        :param content: The content of this Comment.  # noqa: E501
        :type: str
        """

        self._content = content

    @property
    def content_type(self):
        """Gets the content_type of this Comment.  # noqa: E501

        IPFS:0,Magnet:1,HTTP:2,UTF8Text:3,RawBytes:6  # noqa: E501

        :return: The content_type of this Comment.  # noqa: E501
        :rtype: int
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this Comment.

        IPFS:0,Magnet:1,HTTP:2,UTF8Text:3,RawBytes:6  # noqa: E501

        :param content_type: The content_type of this Comment.  # noqa: E501
        :type: int
        """

        self._content_type = content_type

    @property
    def references(self):
        """Gets the references of this Comment.  # noqa: E501


        :return: The references of this Comment.  # noqa: E501
        :rtype: list[CommentRef]
        """
        return self._references

    @references.setter
    def references(self, references):
        """Sets the references of this Comment.


        :param references: The references of this Comment.  # noqa: E501
        :type: list[CommentRef]
        """

        self._references = references

    @property
    def tx_hash(self):
        """Gets the tx_hash of this Comment.  # noqa: E501

        The tx hash  # noqa: E501

        :return: The tx_hash of this Comment.  # noqa: E501
        :rtype: str
        """
        return self._tx_hash

    @tx_hash.setter
    def tx_hash(self, tx_hash):
        """Sets the tx_hash of this Comment.

        The tx hash  # noqa: E501

        :param tx_hash: The tx_hash of this Comment.  # noqa: E501
        :type: str
        """

        self._tx_hash = tx_hash

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Comment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Comment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
