# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse20053(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'height': 'int',
        'timestamp': 'int'
    }

    attribute_map = {
        'height': 'height',
        'timestamp': 'timestamp'
    }

    def __init__(self, height=None, timestamp=None):  # noqa: E501
        """InlineResponse20053 - a model defined in Swagger"""  # noqa: E501

        self._height = None
        self._timestamp = None
        self.discriminator = None

        if height is not None:
            self.height = height
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def height(self):
        """Gets the height of this InlineResponse20053.  # noqa: E501

        Block height  # noqa: E501

        :return: The height of this InlineResponse20053.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this InlineResponse20053.

        Block height  # noqa: E501

        :param height: The height of this InlineResponse20053.  # noqa: E501
        :type: int
        """

        self._height = height

    @property
    def timestamp(self):
        """Gets the timestamp of this InlineResponse20053.  # noqa: E501

        Block timestamp  # noqa: E501

        :return: The timestamp of this InlineResponse20053.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this InlineResponse20053.

        Block timestamp  # noqa: E501

        :param timestamp: The timestamp of this InlineResponse20053.  # noqa: E501
        :type: int
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20053, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20053):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
