# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse20056(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data': 'list[FillOrderInfo]',
        'timesid': 'list[int]'
    }

    attribute_map = {
        'data': 'data',
        'timesid': 'timesid'
    }

    def __init__(self, data=None, timesid=None):  # noqa: E501
        """InlineResponse20056 - a model defined in Swagger"""  # noqa: E501

        self._data = None
        self._timesid = None
        self.discriminator = None

        if data is not None:
            self.data = data
        if timesid is not None:
            self.timesid = timesid

    @property
    def data(self):
        """Gets the data of this InlineResponse20056.  # noqa: E501


        :return: The data of this InlineResponse20056.  # noqa: E501
        :rtype: list[FillOrderInfo]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this InlineResponse20056.


        :param data: The data of this InlineResponse20056.  # noqa: E501
        :type: list[FillOrderInfo]
        """

        self._data = data

    @property
    def timesid(self):
        """Gets the timesid of this InlineResponse20056.  # noqa: E501


        :return: The timesid of this InlineResponse20056.  # noqa: E501
        :rtype: list[int]
        """
        return self._timesid

    @timesid.setter
    def timesid(self, timesid):
        """Sets the timesid of this InlineResponse20056.


        :param timesid: The timesid of this InlineResponse20056.  # noqa: E501
        :type: list[int]
        """

        self._timesid = timesid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20056, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20056):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
