# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Slash(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'validator': 'Address',
        'power': 'str',
        'reason': 'str',
        'jailed': 'bool'
    }

    attribute_map = {
        'validator': 'validator',
        'power': 'power',
        'reason': 'reason',
        'jailed': 'jailed'
    }

    def __init__(self, validator=None, power=None, reason=None, jailed=None):  # noqa: E501
        """Slash - a model defined in Swagger"""  # noqa: E501

        self._validator = None
        self._power = None
        self._reason = None
        self._jailed = None
        self.discriminator = None

        if validator is not None:
            self.validator = validator
        if power is not None:
            self.power = power
        if reason is not None:
            self.reason = reason
        if jailed is not None:
            self.jailed = jailed

    @property
    def validator(self):
        """Gets the validator of this Slash.  # noqa: E501


        :return: The validator of this Slash.  # noqa: E501
        :rtype: Address
        """
        return self._validator

    @validator.setter
    def validator(self, validator):
        """Sets the validator of this Slash.


        :param validator: The validator of this Slash.  # noqa: E501
        :type: Address
        """

        self._validator = validator

    @property
    def power(self):
        """Gets the power of this Slash.  # noqa: E501

        Vote power  # noqa: E501

        :return: The power of this Slash.  # noqa: E501
        :rtype: str
        """
        return self._power

    @power.setter
    def power(self, power):
        """Sets the power of this Slash.

        Vote power  # noqa: E501

        :param power: The power of this Slash.  # noqa: E501
        :type: str
        """

        self._power = power

    @property
    def reason(self):
        """Gets the reason of this Slash.  # noqa: E501


        :return: The reason of this Slash.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this Slash.


        :param reason: The reason of this Slash.  # noqa: E501
        :type: str
        """

        self._reason = reason

    @property
    def jailed(self):
        """Gets the jailed of this Slash.  # noqa: E501


        :return: The jailed of this Slash.  # noqa: E501
        :rtype: bool
        """
        return self._jailed

    @jailed.setter
    def jailed(self, jailed):
        """Sets the jailed of this Slash.


        :param jailed: The jailed of this Slash.  # noqa: E501
        :type: bool
        """

        self._jailed = jailed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Slash, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Slash):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
