# coding: utf-8

"""
    CET-Lite for CoinEx Chain

    A REST interface for state queries, transaction generation and broadcasting.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ValidatorCommission(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'commission_rates': 'ValidatorCommissionCommissionRates',
        'update_time': 'str'
    }

    attribute_map = {
        'commission_rates': 'commission_rates',
        'update_time': 'update_time'
    }

    def __init__(self, commission_rates=None, update_time=None):  # noqa: E501
        """ValidatorCommission - a model defined in Swagger"""  # noqa: E501

        self._commission_rates = None
        self._update_time = None
        self.discriminator = None

        self.commission_rates = commission_rates
        self.update_time = update_time

    @property
    def commission_rates(self):
        """Gets the commission_rates of this ValidatorCommission.  # noqa: E501


        :return: The commission_rates of this ValidatorCommission.  # noqa: E501
        :rtype: ValidatorCommissionCommissionRates
        """
        return self._commission_rates

    @commission_rates.setter
    def commission_rates(self, commission_rates):
        """Sets the commission_rates of this ValidatorCommission.


        :param commission_rates: The commission_rates of this ValidatorCommission.  # noqa: E501
        :type: ValidatorCommissionCommissionRates
        """
        if commission_rates is None:
            raise ValueError("Invalid value for `commission_rates`, must not be `None`")  # noqa: E501

        self._commission_rates = commission_rates

    @property
    def update_time(self):
        """Gets the update_time of this ValidatorCommission.  # noqa: E501


        :return: The update_time of this ValidatorCommission.  # noqa: E501
        :rtype: str
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """Sets the update_time of this ValidatorCommission.


        :param update_time: The update_time of this ValidatorCommission.  # noqa: E501
        :type: str
        """
        if update_time is None:
            raise ValueError("Invalid value for `update_time`, must not be `None`")  # noqa: E501

        self._update_time = update_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ValidatorCommission, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ValidatorCommission):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
